## chendefine/playwright-cdp-selkies

# === SELKIES WHEEL BUILD (auxiliary stage) ===
# Latest upstream docs (docs/start.md + component.md "Python Application"):
# the current Selkies is a single pure-Python wheel that bundles the HTML5 web
# client and pulls pixelflux/pcmflux as dependencies. No release carries that
# wheel yet (releases up to v1.6.2 and PyPI only have the legacy
# selkies_gstreamer package), so per the documented "install from the most
# recent commit" path the wheel is built here from source:
#   1. scripts/ci/build-web.sh bundles the web client into
#      src/selkies/selkies_web (a plain source checkout does NOT contain it),
#   2. python -m build produces the py3-none-any wheel installed in the final
#      stage below.
# node:24 matches the Node version of the final image and satisfies the web
# build; SELKIES_REF is pinned for reproducibility, override with
# --build-arg SELKIES_REF=<sha|branch|tag>.
FROM node:24-bookworm-slim AS selkies-build
ARG SELKIES_REF=4f076052f1eb3214fbf80deed4b18e9e1329bd87
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN git init && \
    git remote add origin https://github.com/selkies-project/selkies.git && \
    git fetch --depth 1 origin "${SELKIES_REF}" && \
    git checkout -q FETCH_HEAD && \
    ./scripts/ci/build-web.sh && \
    pip3 install --no-cache-dir --break-system-packages build && \
    python3 -m build --wheel --outdir /dist

FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
# Container timezone (default UTC = system default; override at build or run
# time, e.g. --build-arg TZ=Asia/Shanghai or -e TZ=Asia/Shanghai).
ARG TZ=UTC
ARG DOCKER_IMAGE_NAME_TEMPLATE=chendefine/playwright-cdp-selkies
ARG NODE_VERSION=24 # autogenerated via ./update-playwright-node.mjs

# playwright-core version from npm, override with: --build-arg PLAYWRIGHT_VERSION=<version>
ARG PLAYWRIGHT_VERSION=1.62.1

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
# Expose the TZ build arg to runtime (Chromium/ICU and most tools read it);
# docker run -e TZ=... overrides it without a rebuild.
ENV TZ=${TZ}

ENV PLAYWRIGHT_BROWSERS_PATH=/usr/local/share/ms-playwright

# bash + pipefail so RUN pipes (curl | gpg, ...) fail fast
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# === INSTALL Node.js ===

RUN --mount=type=secret,id=npmrc,target=/root/.npmrc,required=false \
    apt-get update && \
    apt-get install -y --no-install-recommends curl wget gpg ca-certificates tzdata && \
    mkdir -p /etc/apt/keyrings && \
    curl -sL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_VERSION}.x nodistro main" >> /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends nodejs && \
    # Feature-parity with node.js base images.
    apt-get install -y --no-install-recommends git openssh-client && \
    npm install -g yarn && \
    # clean apt cache
    rm -rf /var/lib/apt/lists/* && \
    # Create the pwuser
    adduser pwuser

# === BAKE BROWSERS INTO IMAGE ===
# Browsers are split into separate layers to enable parallel pulls.

# 1. Download the playwright-core package from the npm registry.
#    curl -f fails the build fast if PLAYWRIGHT_VERSION does not exist (404).
RUN curl -fsSL "https://registry.npmjs.org/playwright-core/-/playwright-core-${PLAYWRIGHT_VERSION}.tgz" \
    -o /tmp/playwright-core.tar.gz

# 2. Set up playwright-core and install all system dependencies and install chromium browser in one layer.
# Note: installing chromium also installs chromium-headless-shell and ffmpeg.
# The agent dir is created, used and deleted ENTIRELY inside this one RUN, so
# it leaves no trace in the image. Do NOT replace the `cd` with WORKDIR here:
# WORKDIR is image-config metadata that survives the rm below — the runtime
# would then re-create an empty /ms-playwright-agent in every container and
# make it the working directory.
RUN install -d -m 777 "${PLAYWRIGHT_BROWSERS_PATH}" "${PLAYWRIGHT_BROWSERS_PATH}/.links" && \
    mkdir /ms-playwright-agent && \
    cd /ms-playwright-agent && npm init -y && \
    npm i /tmp/playwright-core.tar.gz && \
    npm exec --no -- playwright-core mark-docker-image "${DOCKER_IMAGE_NAME_TEMPLATE}" && \
    npm exec --no -- playwright-core install-deps && \
    npm exec --no -- playwright-core install chromium && \
    chmod -R 777 "${PLAYWRIGHT_BROWSERS_PATH}"/chromium-* "${PLAYWRIGHT_BROWSERS_PATH}"/chromium_headless_shell-* "${PLAYWRIGHT_BROWSERS_PATH}"/ffmpeg-* && \
    rm -rf /var/lib/apt/lists/* && \
    rm /tmp/playwright-core.tar.gz && \
    rm -rf /ms-playwright-agent && \
    rm -rf ~/.npm/

# === NGINX FRONT DOOR (CDP gateway + web reverse proxy) ===
# nginx fronts every public port (replaces the previous socat forwarder) on
# FIXED container ports (host-side publishing is docker's -p / compose ports):
#   * 0.0.0.0:80   -> Selkies web UI over HTTP (always on)
#   * 0.0.0.0:443  -> Selkies web UI over TLS (only when the container is
#     started with ENABLE_HTTPS=true; nginx does not listen on 443 otherwise.
#     The certificate pair is reused whenever a valid one exists — mounted in
#     /etc/nginx/tls, or generated on an earlier start — and a self-signed
#     pair is generated only when no usable pair is found)
#   * 0.0.0.0:9222 -> chromium loopback DevTools port. Chromium >= 111 ignores
#     --remote-debugging-address and binds DevTools to loopback only, so nginx
#     forwards the public port there. Unlike socat's raw TCP forward this is
#     an HTTP-level proxy that also speaks WebSocket (the DevTools protocol
#     runs over WebSocket), handled via the upgrade headers in the config
#     generated by docker-entrypoint.sh.
RUN apt-get update && \
    apt-get install -y --no-install-recommends nginx openssl && \
    rm -rf /var/lib/apt/lists/*

# === SELKIES REMOTE DESKTOP ===
# Installed per the upstream Ubuntu instructions (selkies docs/start.md).
# Selkies serves the HTML5 web client, signaling and media on a single port
# (default 8080) over WebSockets; WebRTC is opt-in with --mode=webrtc.

# Step 1: system dependencies from the documented Ubuntu/Debian list
# (curl/ca-certificates are already installed above). libva2/mesa-va-drivers
# cover the documented optional VA-API path for hardware H.264 on Intel/AMD
# GPUs; NVENC comes from the host-injected NVIDIA driver.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev jq xserver-xorg-core xvfb \
    x11-utils x11-xkb-utils x11-xserver-utils wmctrl libx11-xcb1 \
    libxcb-dri3-0 libxkbcommon0 libxdamage1 libxfixes3 libxtst6 \
    libxext6 libpulse0 pulseaudio libva2 mesa-va-drivers && \
    rm -rf /var/lib/apt/lists/*

# Step 2: the Selkies Python package (wheel built in the selkies-build stage).
# pip resolves pixelflux/pcmflux and the rest as prebuilt manylinux wheels, so
# no compiler is needed. Installs the `selkies`, `selkies-resize` and
# `selkies-gpu-probe` console commands.
COPY --from=selkies-build /dist/selkies-*.whl /tmp/
RUN PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install --no-cache-dir --force-reinstall \
    /tmp/selkies-*.whl && \
    rm -f /tmp/selkies-*.whl && \
    rm -rf ~/.cache/pip && \
    # smoke-test the console commands and the bundled web client
    selkies --help >/dev/null && \
    command -v selkies-resize selkies-gpu-probe >/dev/null && \
    python3 -c "import importlib.resources as r; assert (r.files('selkies.selkies_web') / 'index.html').is_file(), 'web client missing'"

# Step 3: Selkies attaches to an existing X display and PulseAudio server.
# docker-entrypoint.sh starts both (Xvfb + PulseAudio) plus Selkies (bound to
# loopback), the playwright Chromium and the nginx front door in one place, so
# container start is service start; combine with `docker run --restart=always`
# for boot persistence.
ENV DISPLAY=":0"
ENV XDG_RUNTIME_DIR="/tmp"
ENV PULSE_RUNTIME_PATH="/tmp/pulse"
ENV PULSE_SERVER="unix:/tmp/pulse/native"
ENV PIPEWIRE_LATENCY="256/48000"

# Ports as served INSIDE the container (all by nginx, fixed by design):
# 80 = web UI over HTTP (always), 443 = web UI over HTTPS (only when run with
# ENABLE_HTTPS=true — nginx does not listen on 443 otherwise), 9222 = chromium
# CDP endpoint. Host-side ports are chosen by docker run -p / compose ports.
EXPOSE 80 443 9222

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh

# Container start == services start. Any argument other than "start" is exec'd
# instead, e.g. `docker run -it <image> bash`.
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

