## chendefine/playwright-cdp-selkies

FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
# Container timezone (default UTC = system default; override at build or run
# time, e.g. --build-arg TZ=Asia/Shanghai or -e TZ=Asia/Shanghai).
ARG TZ=UTC
ARG DOCKER_IMAGE_NAME_TEMPLATE=chendefine/playwright-cdp-selkies
ARG NODE_VERSION=24 # autogenerated via ./update-playwright-node.mjs

# playwright-core version from npm, override with: --build-arg PLAYWRIGHT_VERSION=<version>
ARG PLAYWRIGHT_VERSION=1.63.0

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
# Expose the TZ build arg to runtime (Chromium/ICU and most tools read it);
# docker run -e TZ=... overrides it without a rebuild.
ENV TZ=${TZ}

ENV PLAYWRIGHT_BROWSERS_PATH=/usr/local/share/ms-playwright

# bash + pipefail so RUN pipes (curl | gpg, ...) fail fast
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# === INSTALL Node.js ===

RUN --mount=type=secret,id=npmrc,target=/root/.npmrc,required=false \
    apt-get update && \
    apt-get install -y --no-install-recommends curl wget gpg ca-certificates tzdata && \
    mkdir -p /etc/apt/keyrings && \
    curl -sL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_VERSION}.x nodistro main" >> /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends nodejs && \
    # Feature-parity with node.js base images.
    apt-get install -y --no-install-recommends git openssh-client && \
    npm install -g yarn && \
    # clean apt cache
    rm -rf /var/lib/apt/lists/* && \
    # Create the pwuser
    adduser pwuser

# === BAKE BROWSERS INTO IMAGE ===
# Browsers are split into separate layers to enable parallel pulls.

# 1. Download the playwright-core package from the npm registry.
#    curl -f fails the build fast if PLAYWRIGHT_VERSION does not exist (404).
RUN curl -fsSL "https://registry.npmjs.org/playwright-core/-/playwright-core-${PLAYWRIGHT_VERSION}.tgz" \
    -o /tmp/playwright-core.tar.gz

# 2. Set up playwright-core and install all system dependencies and install chromium browser in one layer.
# Note: installing chromium also installs chromium-headless-shell and ffmpeg.
# The agent dir is created, used and deleted ENTIRELY inside this one RUN, so
# it leaves no trace in the image. Do NOT replace the `cd` with WORKDIR here:
# WORKDIR is image-config metadata that survives the rm below — the runtime
# would then re-create an empty /ms-playwright-agent in every container and
# make it the working directory.
RUN install -d -m 777 "${PLAYWRIGHT_BROWSERS_PATH}" "${PLAYWRIGHT_BROWSERS_PATH}/.links" && \
    mkdir /ms-playwright-agent && \
    cd /ms-playwright-agent && npm init -y && \
    npm i /tmp/playwright-core.tar.gz && \
    npm exec --no -- playwright-core mark-docker-image "${DOCKER_IMAGE_NAME_TEMPLATE}" && \
    npm exec --no -- playwright-core install-deps && \
    npm exec --no -- playwright-core install chromium && \
    chmod -R 777 "${PLAYWRIGHT_BROWSERS_PATH}"/chromium-* "${PLAYWRIGHT_BROWSERS_PATH}"/chromium_headless_shell-* "${PLAYWRIGHT_BROWSERS_PATH}"/ffmpeg-* && \
    rm -rf /var/lib/apt/lists/* && \
    rm /tmp/playwright-core.tar.gz && \
    rm -rf /ms-playwright-agent && \
    rm -rf ~/.npm/

# === NGINX FRONT DOOR (CDP gateway + web reverse proxy) ===
# nginx fronts every public port (replaces the previous socat forwarder) on
# FIXED container ports (host-side publishing is docker's -p / compose ports):
#   * 0.0.0.0:80   -> Selkies web UI over HTTP (always on)
#   * 0.0.0.0:443  -> Selkies web UI over TLS (only when the container is
#     started with ENABLE_HTTPS=true; nginx does not listen on 443 otherwise.
#     The certificate pair is reused whenever a valid one exists — mounted in
#     /etc/nginx/tls, or generated on an earlier start — and a self-signed
#     pair is generated only when no usable pair is found)
#   * 0.0.0.0:9222 -> chromium loopback DevTools port. Chromium >= 111 ignores
#     --remote-debugging-address and binds DevTools to loopback only, so nginx
#     forwards the public port there. Unlike socat's raw TCP forward this is
#     an HTTP-level proxy that also speaks WebSocket (the DevTools protocol
#     runs over WebSocket), handled via the upgrade headers in the config
#     generated by docker-entrypoint.sh.
RUN apt-get update && \
    apt-get install -y --no-install-recommends nginx openssl && \
    rm -rf /var/lib/apt/lists/*

# === SELKIES REMOTE DESKTOP ===
# Installed per the upstream Ubuntu instructions (selkies docs/start.md).
# Selkies serves the HTML5 web client, signaling and media on a single port
# (default 8080) over WebSockets; WebRTC is opt-in with --mode=webrtc.

# Step 1: system dependencies from the documented Ubuntu/Debian list
# (curl/ca-certificates are already installed above). libva2/mesa-va-drivers
# cover the documented optional VA-API path for hardware H.264 on Intel/AMD
# GPUs; NVENC comes from the host-injected NVIDIA driver.
# GPU-passthrough userland (compose.gpu.yaml / compose.gpu-nvidia.yaml):
# libgl1-mesa-dri = Mesa GL/EGL drivers (iris/radeonsi/...) so chromium can
# render on a passed-through Intel/AMD GPU; mesa-vulkan-drivers + libvulkan1
# = the Vulkan ICDs chromium's default ANGLE/Vulkan backend renders through
# (works on the Xvfb display: offscreen rendering + xcb present, no
# window-system GL visuals needed); intel-media-va-driver-non-free = Intel
# VA-API for Broadwell+ (mesa-va-drivers already covers AMD and older
# Intel); mesa-utils/vainfo/vulkan-tools = verification tools.
# NVIDIA GL/EGL/Vulkan userland is intentionally NOT installed here — the
# nvidia container toolkit injects host-matching libraries at runtime.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev jq xserver-xorg-core xvfb \
    x11-utils x11-xkb-utils x11-xserver-utils wmctrl libx11-xcb1 \
    libxcb-dri3-0 libxkbcommon0 libxdamage1 libxfixes3 libxtst6 \
    libxext6 libpulse0 pulseaudio libva2 mesa-va-drivers \
    libgl1-mesa-dri intel-media-va-driver-non-free mesa-utils vainfo \
    libvulkan1 mesa-vulkan-drivers vulkan-tools && \
    rm -rf /var/lib/apt/lists/*

# The NVIDIA Vulkan ICD manifest (nvidia_icd.json) arrives with the toolkit
# injection — CDI mounts it at /etc/vulkan/icd.d, the legacy hook at
# /usr/share/vulkan/icd.d — and the Ubuntu loader scans both paths, so
# nothing is baked here on purpose: a static copy would make the loader
# enumerate the GPU twice (verified: GPU0/GPU1 duplicates).

# Step 2: the Selkies Python package, installed from the official upstream
# release artifacts (docs.selkies.io). Selkies 2.0 is a single pure-Python
# wheel that bundles the HTML5 web client; the 2.0.0rc0 wheel ships only on
# the GitHub release (RCs are not published to PyPI), and it pins
# pixelflux~=2.1.0rc0 and pcmflux~=2.1.0rc0, which likewise exist only on
# their own GitHub releases. All three wheels are therefore fetched pinned by
# sha256 (digests from the GitHub release API) and installed together; pip
# resolves the remaining dependencies from PyPI as prebuilt manylinux wheels,
# so no compiler is needed. Installs the `selkies`, `selkies-resize` and
# `selkies-gpu-probe` console commands.
# ubuntu:24.04 ships Python 3.12 -> SELKIES_PYTAG=cp312; if the base image's
# Python ever moves, bump SELKIES_PYTAG and the two dependency digests (the
# selkies wheel itself is py3-none-any and arch-independent).
ARG SELKIES_VERSION=2.0.0rc0
ARG PIXELFLUX_VERSION=2.1.0rc0
ARG PCMFLUX_VERSION=2.1.0rc0
ARG SELKIES_PYTAG=cp312
# sha256 of selkies-${SELKIES_VERSION}-py3-none-any.whl
ARG SELKIES_SHA256=f080aea3dab0e926fafdf7a91e7d02c681f56ff02186264026716248a632238d
# sha256 of pixelflux-${PIXELFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_<arch>.whl
ARG PIXELFLUX_SHA256_AMD64=a143af92bed38b75e60356227a587e8f8e20bc5e1c29511f7b02d245321b0ae7
ARG PIXELFLUX_SHA256_ARM64=d2e95890da4f7d028063dc32d92a006fc430da163fc9ae5645da5bc27dce761e
# sha256 of pcmflux-${PCMFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_<arch>.whl
ARG PCMFLUX_SHA256_AMD64=25bb510c250587cbf178e8e83cbe8ac426db6978de16a8d7b40e742d780537aa
ARG PCMFLUX_SHA256_ARM64=c659d589e38bd14d754b8b048a732486d953bdb29ccf78a1334be6c9534f7d32
# TARGETARCH (amd64/arm64) is supplied automatically by the builder.
ARG TARGETARCH
RUN case "${TARGETARCH}" in \
        amd64) WHL_ARCH=x86_64;  PXL_SHA="${PIXELFLUX_SHA256_AMD64}"; PCM_SHA="${PCMFLUX_SHA256_AMD64}" ;; \
        arm64) WHL_ARCH=aarch64; PXL_SHA="${PIXELFLUX_SHA256_ARM64}"; PCM_SHA="${PCMFLUX_SHA256_ARM64}" ;; \
        *) printf 'unsupported TARGETARCH: %s\n' "${TARGETARCH:-<unset>}" >&2; exit 1 ;; \
    esac && \
    curl -fsSL --retry 3 -o "/tmp/selkies-${SELKIES_VERSION}-py3-none-any.whl" \
        "https://github.com/selkies-project/selkies/releases/download/${SELKIES_VERSION}/selkies-${SELKIES_VERSION}-py3-none-any.whl" && \
    echo "${SELKIES_SHA256}  /tmp/selkies-${SELKIES_VERSION}-py3-none-any.whl" | sha256sum -c - && \
    curl -fsSL --retry 3 -o "/tmp/pixelflux-${PIXELFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_${WHL_ARCH}.whl" \
        "https://github.com/selkies-project/pixelflux/releases/download/${PIXELFLUX_VERSION}/pixelflux-${PIXELFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_${WHL_ARCH}.whl" && \
    echo "${PXL_SHA}  /tmp/pixelflux-${PIXELFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_${WHL_ARCH}.whl" | sha256sum -c - && \
    curl -fsSL --retry 3 -o "/tmp/pcmflux-${PCMFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_${WHL_ARCH}.whl" \
        "https://github.com/selkies-project/pcmflux/releases/download/${PCMFLUX_VERSION}/pcmflux-${PCMFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_${WHL_ARCH}.whl" && \
    echo "${PCM_SHA}  /tmp/pcmflux-${PCMFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_${WHL_ARCH}.whl" | sha256sum -c - && \
    PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install --no-cache-dir \
        "/tmp/selkies-${SELKIES_VERSION}-py3-none-any.whl" \
        "/tmp/pixelflux-${PIXELFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_${WHL_ARCH}.whl" \
        "/tmp/pcmflux-${PCMFLUX_VERSION}-${SELKIES_PYTAG}-${SELKIES_PYTAG}-manylinux_2_28_${WHL_ARCH}.whl" && \
    rm -f /tmp/selkies-*.whl /tmp/pixelflux-*.whl /tmp/pcmflux-*.whl && \
    rm -rf ~/.cache/pip && \
    # smoke-test the console commands, the exact version and the bundled web client
    selkies --help >/dev/null && \
    selkies --version | grep -qx "selkies ${SELKIES_VERSION}" && \
    command -v selkies-resize selkies-gpu-probe >/dev/null && \
    python3 -c "import importlib.resources as r; assert (r.files('selkies.selkies_web') / 'index.html').is_file(), 'web client missing'"

# Step 3: Selkies attaches to an existing X display and PulseAudio server.
# docker-entrypoint.sh starts both (Xvfb + PulseAudio) plus Selkies (bound to
# loopback), the playwright Chromium and the nginx front door in one place, so
# container start is service start; combine with `docker run --restart=always`
# for boot persistence.
ENV DISPLAY=":0"
ENV XDG_RUNTIME_DIR="/tmp"
ENV PULSE_RUNTIME_PATH="/tmp/pulse"
ENV PULSE_SERVER="unix:/tmp/pulse/native"
ENV PIPEWIRE_LATENCY="256/48000"

# Ports as served INSIDE the container (all by nginx, fixed by design):
# 80 = web UI over HTTP (always), 443 = web UI over HTTPS (only when run with
# ENABLE_HTTPS=true — nginx does not listen on 443 otherwise), 9222 = chromium
# CDP endpoint. Host-side ports are chosen by docker run -p / compose ports.
EXPOSE 80 443 9222

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh

# Container start == services start. Any argument other than "start" is exec'd
# instead, e.g. `docker run -it <image> bash`.
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

